introduced versioning scheme and associated ci/cd and scripts for management

diff --git a/.github/workflows/release-build-deploy.yml b/.github/workflows/release-build-deploy.yml
--- a/.github/workflows/release-build-deploy.yml
+++ b/.github/workflows/release-build-deploy.yml
@@ -1,21 +1,13 @@
-name: Release and Deploy to GitHub Pages
+name: Release, Build, and Deploy
+
 on:
   push:
     branches:
       - main
-  workflow_dispatch:
-
-permissions:
-  contents: write
-  pages: write
-  id-token: write
-
-concurrency:
-  group: "pages"
-  cancel-in-progress: false
 
 jobs:
   release:
+    name: Release
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -26,10 +18,20 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 'lts/*'
-      - name: Install Node dependencies
-        run: npm ci
+      - name: Install dependencies
+        run: |
+          npm ci
+          if [ $? -ne 0 ]; then
+            echo "Failed to install dependencies"
+            exit 1
+          fi
       - name: Generate changelog
-        run: node generate-changelog.js
+        run: |
+          node generate-changelog.js
+          if [ $? -ne 0 ]; then
+            echo "Failed to generate changelog"
+            exit 1
+          fi
       - name: Release project
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -42,22 +44,39 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          set -e
           for license in docs/licenses/*/*/; do
             if [ -f "$license/package.json" ]; then
               echo "Releasing $license"
-              (cd $license && npx semantic-release -e ../../../.releaserc.json)
+              (
+                cd $license
+                npx semantic-release -e ../../../.releaserc.json
+                if [ $? -ne 0 ]; then
+                  echo "Failed to release $license"
+                  exit 1
+                fi
+              )
             fi
           done
       - name: Commit updated changelogs
         run: |
-          git config --local user.name github-actions[bot]
-          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
           git add CHANGELOG.md docs/licenses/**/CHANGELOG.md
           git diff-index --quiet HEAD || git commit -m "docs: update changelogs [skip ci]"
+          if [ $? -ne 0 ]; then
+            echo "Failed to commit updated changelogs"
+            exit 1
+          fi
           git push
+          if [ $? -ne 0 ]; then
+            echo "Failed to push changes"
+            exit 1
+          fi
 
-  deploy:
+  build:
     needs: release
+    name: Build
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -86,9 +105,36 @@ jobs:
           export PYTHONPATH=$PYTHONPATH:custom_extensions
           pip install --upgrade pip
           pip install markdown pymdown-extensions mkdocs-material[imaging] mkdocs-static-i18n[material] mkdocs-git-revision-date-localized-plugin mkdocs-git-authors-plugin mkdocs-rss-plugin mkdocs[i18n] pygments pyyaml mkdocs-hooks-plugin
-      - name: Build and deploy
-        id: deployment
-        run: mkdocs gh-deploy --force
+      - name: Build MkDocs site
+        run: |
+          mkdocs build
+          if [ $? -ne 0 ]; then
+            echo "Failed to build MkDocs site"
+            exit 1
+          fi
+      - name: Upload built site
+        uses: actions/upload-artifact@v3
+        with:
+          name: site
+          path: site
+
+  deploy:
+    needs: build
+    name: Deploy
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Download built site
+        uses: actions/download-artifact@v3
+        with:
+          name: site
+          path: site
+      - name: Deploy mkdocs
+        run: |
+          git config user.name github-actions[bot]
+          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
+          mkdocs gh-deploy --force
 
   notify:
     needs: [release, deploy]
